from django.urls import path
from .views_apis import *

urlpatterns = [
    path('user/', UserAPIView.as_view(), name='users'),
    path('simple-transaction/', SpecialTransactionCreateAPIView.as_view(), name='simple_transaction_creation'),
    path('account-receivable/', AccountReceivableAPIView.as_view(), name='account_receivable'),
    path('account-receivable/<str:reference_number>/', AccountReceivableAPIView.as_view(), name='account_receivable_update'),
    path('user-financial-account-mapping/', UserFinancialAccountMappingAPIView.as_view(), name='user_financial_account_mapping'),
    path('user-financial-account-category/', UserFinancialAccountCategoryAPIView.as_view(), name='user_financial_account_category'),
    path('account-category/', AccountCategoryAPIView.as_view(), name='account_category'),
    path('company/', CompanyAPIView.as_view(), name='company'),
    path('company-update/<pk>/', CompanyUpdateAPIView.as_view(), name='company_update'),
    path('branch/', BranchAPIView.as_view(), name='branch'),
    path('currency/', CurrencyAPIView.as_view(), name='currency'),
    path('account-type/', AccountTypeAPIView.as_view(), name='account_type'),
    path('account-holder/', AccountHolderAPIView.as_view(), name='account_holder'),
    path('asset-type/', AssetTypeAPIView.as_view(), name='asset_type'),
    path('gl-line/', GLLineAPIView.as_view(), name='gl_line'),
    path('accounts/', AccountsAPIView.as_view(), name='accounts'),
    path('overdraft-limit/', OverdraftLimitAPIView.as_view(), name='overdraft_limit'),
    path('account-restriction/', AccountRestrictionAPIView.as_view(), name='account_restriction'),
    path('transaction-code/', TransactionCodeAPIView.as_view(), name='transaction_code'),
    path('charge-code/', ChargeCodeAPIView.as_view(), name='charge_code'),
    path('transaction-type/', TransactionTypeAPIView.as_view(), name='transaction_type'),
    path('transaction-type-classification/', TransactionTypeClassificationAPIView.as_view(), name='transaction_type_classification'),
    path('transaction-type-mode/', TransactionTypeModeAPIView.as_view(), name='transaction_type_mode'),
    path('transaction-detail/', TransactionDetailAPIView.as_view(), name='transaction_detail'),
    path('teller-profile/', TellerProfileAPIView.as_view(), name='teller_profile'),
    path('reference-type/', ReferenceTypeAPIView.as_view(), name='reference_type'),
    path('payment-complexity/', PaymentComplexityAPIView.as_view(), name='payment_complexity'),
    path('account-payable/', AccountPayableAPIView.as_view(), name='account_payable'),
    path('payment/', PaymentAPIView.as_view(), name='payment'),
    path('receipt/', ReceiptAPIView.as_view(), name='receipt'),
    path('receivable-and-payable-transaction/', ReceivableAndPayableTransactionAPIView.as_view(), name='receivable_and_payable_transaction'),

    path('common-registration/', CommonRegistrationAPIView.as_view(), name='common_registration'),
    path('all-transaction/', AllTransactionAPIView.as_view(), name='all_transaction'),
    path('funds-transfer/', FundsTransferAPIView.as_view(), name='funds_Transfer'),
    path('bank-list/', BankRegistrationAPIView.as_view(), name='bank_list'),
    path('bank-to-member-funds-transfer/', FundsTransferBankToMemberAccountAPIView.as_view(), name='funds_transfer_bank_member_acc'),
    path('member-to-bank-funds-transfer/', FundsTransferMemberToBankAccountAPIView.as_view(), name='funds_transfer_member_bank_acc'),
    path('get-company-account/<str:company_id>/', GetCompanyAccountNumberAPIView.as_view(), name='get_company_account_api_views'),
    path('sign-up/', SignUpAPIView.as_view(), name='sign_up_apis'),

]
